import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Cinzel, Crimson_Text, Spectral } from 'next/font/google'
import "./globals.css";
import LoadingScreen from "../components/LoadingScreen";


const cinzel = Cinzel({
  variable: '--font-display',
  subsets: ['latin'],
})

const crimsonText = Crimson_Text({
  weight: ['400', '600'],
  variable: '--font-serif',
  subsets: ['latin'],
})

const spectral = Spectral({
  weight: ['400', '600'],
  variable: '--font-body',
  subsets: ['latin'],
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${cinzel.variable} ${crimsonText.variable} ${spectral.variable}  ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <LoadingScreen />
      </body>
    </html>
  );
}
